// TRANSLATIONS
const translations = {
    tr: {
        // Navigation
        "nav.problem": "Problem",
        "nav.solution": "Çözüm",
        "nav.market": "Pazar",
        "nav.traction": "Çekiş",
        "nav.financials": "Finansal",
        "nav.team": "Ekip",
        "nav.calculator": "Hesaplayıcı",
        "nav.dataroom": "Data Room Erişim",
        
        // Hero Section
        "hero.badge": "Dünyanın İlk Hibrit Karbon Borsası",
        "hero.title": "Karbon Ekonomisinin Geleceği",
        "hero.subtitle": "CBAM 2026 uyumu, blockchain doğrulama, çok taraflı pazar ile $70B+ küresel pazarda liderlik",
        "hero.dataroom": "Data Room'a Erişim",
        "hero.seed": "Seed Round",
        
        // Unicorn Section
        "unicorn.badge": "Unicorn Potansiyeli",
        "unicorn.title": "$1B+ Değerleme Yolu",
        "unicorn.subtitle": "Küresel karbon piyasasında benzersiz pozisyon ve büyüme potansiyeli",
        "unicorn.card1.title": "$70B+ Küresel Pazar",
        "unicorn.card1.desc": "2030'da $300B+ büyüme projeksiyonu",
        "unicorn.card2.title": "15,000+ Şirket",
        "unicorn.card2.desc": "CBAM zorunluluğu ile acil çözüm ihtiyacı",
        "unicorn.card3.title": "Teknoloji Liderliği",
        "unicorn.card3.desc": "Blockchain + IoT + AI kombinasyonu",
        "unicorn.card4.title": "4 Segment Pazar",
        "unicorn.card4.desc": "Bireysel + Çiftçi + Kurumsal + Trader",
        "unicorn.decacorn": "📈 $10B+ Decacorn Yol Haritası",
        "unicorn.timeline1.title": "Seed Aşaması",
        "unicorn.timeline1.desc": "MVP geliştirme ve pilot müşteriler",
        "unicorn.timeline2.title": "Series A & Büyüme",
        "unicorn.timeline2.desc": "Pazar liderliği ve bölgesel genişleme",
        "unicorn.timeline3.title": "Unicorn Aşaması",
        "unicorn.timeline3.desc": "$1B+ değerleme ve küresel operasyonlar",
        "unicorn.timeline4.title": "Decacorn Potansiyeli",
        "unicorn.timeline4.desc": "$10B+ değerleme ve endüstri liderliği",
        
        // Problem Section
        "problem.badge": "Acil Çözüm Gerekiyor",
        "problem.title": "CBAM 2026 Krizi",
        "problem.subtitle": "Türk ihracatçılar için €50-100/ton karbon cezası riski",
        "problem.card1.title": "15,000+ Türk İhracatçı",
        "problem.card1.desc": "AB'ye ihracat yapan tüm firmalar risk altında",
        "problem.card2.title": "$40B İhracat Riski",
        "problem.card2.desc": "Türkiye'nin yıllık AB ihracatı tehlikede",
        "problem.card3.title": "€50-100/ton Cezalar",
        "problem.card3.desc": "Uyumsuzluk başına ağır mali yaptırımlar",
        "problem.card4.title": "Manuel Çözüm İmkansız",
        "problem.card4.desc": "Binlerce tedarikçi, karmaşık karbon hesaplama",
        "problem.quote.text": "\"Üyelerimiz panikleme yaşıyor. CBAM hesaplama için acil çözüm lazım.\"",
        "problem.quote.author": "- Türkiye İhracatçılar Meclisi (TİM)",
        
        // Solution Section
        "solution.badge": "Teknoloji Çözümü",
        "solution.title": "6 Temel Teknoloji Modülü",
        "solution.subtitle": "Kapsamlı karbon yönetimi için entegre platform",
        "solution.card1.title": "CBAM Uyum Motoru",
        "solution.card1.item1": "AI destekli karbon hesaplama",
        "solution.card1.item2": "ERP entegrasyonu",
        "solution.card1.item3": "Otomatik raporlama",
        "solution.card1.item4": "Tedarikçi yönetimi",
        "solution.card2.title": "Blockchain Registry",
        "solution.card2.item1": "Polygon network (ERC-1155)",
        "solution.card2.item2": "Değiştirilemez karbon kredileri",
        "solution.card2.item3": "Şeffaf takip",
        "solution.card2.item4": "Akıllı kontratlar",
        "solution.card3.title": "IoT MRV Sistemi",
        "solution.card3.item1": "Gerçek zamanlı ölçüm",
        "solution.card3.item2": "Sensör entegrasyonu",
        "solution.card3.item3": "Otomatik doğrulama",
        "solution.card3.item4": "Veri güvenliği",
        "solution.card4.title": "Çok Taraflı Pazar",
        "solution.card4.item1": "Bireysel kullanıcılar",
        "solution.card4.item2": "Çiftçiler",
        "solution.card4.item3": "Kurumsal müşteriler",
        "solution.card4.item4": "Profesyonel traderlar",
        "solution.card5.title": "API & Entegrasyon",
        "solution.card5.item1": "RESTful API",
        "solution.card5.item2": "Webhooks",
        "solution.card5.item3": "SDK (Python, Node.js, Java)",
        "solution.card5.item4": "White-label çözüm",
        "solution.card6.title": "Enterprise Security",
        "solution.card6.item1": "SOC2 Type II",
        "solution.card6.item2": "ISO 27001",
        "solution.card6.item3": "GDPR uyumlu",
        "solution.card6.item4": "Penetrasyon testi",
        
        // Competitive Section
        "competitive.badge": "Rekabet Avantajı",
        "competitive.title": "Piyasa Liderliği",
        "competitive.subtitle": "Dünyada tek: 4 kullanıcı segmentini birleştiren platform",
        "competitive.table.header1": "Özellik",
        "competitive.table.header2": "CarbonEcoMarket",
        "competitive.table.row1.feature": "CBAM 2026 Uyumu",
        "competitive.table.row1.carbon": "Tam uyum",
        "competitive.table.row2.feature": "Blockchain Doğrulama",
        "competitive.table.row2.carbon": "Polygon",
        "competitive.table.row3.feature": "IoT MRV Sistemi",
        "competitive.table.row3.carbon": "Gerçek zaman",
        "competitive.table.row4.feature": "Çok Taraflı Pazar",
        "competitive.table.row4.carbon": "4 Segment",
        "competitive.research.title": "Pazar Araştırması Sonuçları",
        "competitive.research.item1": "Dünyada Tek: Bireysel karbon hesaplama + sıfırlama",
        "competitive.research.item2": "Dünyada Tek: Çiftçiler için karbon satış platformu",
        "competitive.research.item3": "Dünyada Tek: Trader + Bireysel + Kurumsal tek platform",
        
        // Market Section
        "market.badge": "Pazar Fırsatı",
        "market.title": "$70B Global Karbon Pazarı",
        "market.subtitle": "2030'da $300B+ büyüme projeksiyonu ile hızla büyüyen pazar",
        "market.tam.title": "$70B+",
        "market.tam.subtitle": "Global Karbon Piyasası (2025)",
        "market.sam.title": "$5B",
        "market.sam.subtitle": "MENA + Türkiye Bölgesi",
        "market.som.title": "$500M",
        "market.som.subtitle": "3. Yıl Hedef",
        "market.value.title": "Benzersiz Değer Önerisi",
        "market.value.text": "Hiçbir platform bireysel kullanıcı + çiftçi + kurumsal + trader'ı tek çatı altında birleştirmiyor. Biz bunu yapan ilk ve tek platformuz!",
        
        // Traction Section
        "traction.badge": "Çekiş & Doğrulama",
        "traction.title": "İlerleme & Başarılar",
        "traction.subtitle": "Pazar validasyonu ve stratejik ilerleme",
        "traction.card1.title": "12 LOI İmzalandı",
        "traction.card1.item1": "50K ton/yıl pipeline",
        "traction.card1.item2": "$10M+ potansiyel ARR",
        "traction.card1.item3": "Pilot müşteriler hazır",
        "traction.card2.title": "3 C-Level Danışman",
        "traction.card2.item1": "Selim Güven - ACWA Power",
        "traction.card2.item2": "Hüseyin Yeğin - Borusan EnBW",
        "traction.card2.item3": "Ilgın Sözen - ÇEKÜL Vakfı",
        "traction.card3.title": "MVP Q1 2026",
        "traction.card3.item1": "Blockchain testnet aktif",
        "traction.card3.item2": "CBAM modülü test aşamasında",
        "traction.card3.item3": "25+ firma pilot pipeline",
        "traction.card4.title": "Stratejik Ortaklıklar",
        "traction.card4.item1": "TİM (Türkiye İhracatçılar Meclisi)",
        "traction.card4.item2": "İGEME (İhracatı Geliştirme Merkezi)",
        "traction.card4.item3": "Teknoloji partnerleri: Polygon, AWS",
        
        // Financials Section
        "financials.badge": "Finansal Projeksiyonlar",
        "financials.title": "3 Senaryo ile Büyüme Yol Haritası",
        "financials.subtitle": "2026-2035 gelir ve değerleme tahminleri",
        "financials.conservative": "Muhafazakar",
        "financials.base": "Temel",
        "financials.aggressive": "İyimser",
        "financials.year": "Yıl",
        "financials.revenue": "Ciro",
        "financials.arr": "ARR",
        "financials.customers": "Müşteri",
        "financials.investment": "Yatırım",
        "financials.valuation": "Değerleme",
        "financials.rounds": "💵 Yatırım Turları",
        
        // Revenue & Funds
        "revenue.badge": "Gelir Modelleri",
        "revenue.title": "6 Gelir Modeli - 2028 Dağılımı",
        "revenue.subtitle": "Çok katmanlı gelir modeli ile finansal sürdürülebilirlik",
        "funds.badge": "Yatırım Kullanımı",
        "funds.title": "Seed Yatırımı Kullanım Planı ($1.5-2M)",
        "funds.subtitle": "Stratejik kaynak dağılımı ile maksimum büyüme",
        
        // Team Section
        "team.badge": "Ekibimiz",
        "team.title": "Deneyimli Liderlik Ekibi",
        "team.subtitle": "Karbon piyasasını şekillendiren uzman ekip",
        "team.role1": "Kurucu & CEO",
        "team.bio1": "Lionexia kurucusu, 15+ yıl fintech deneyimi",
        "team.role2": "CTO & Kurucu Ortak",
        "team.bio2": "18+ yıl yazılım ve blockchain deneyimi",
        "team.role3": "Danışman",
        "team.bio3": "ACWA Power - Enerji sektörü uzmanı",
        "team.role4": "Danışman",
        "team.bio4": "Borusan EnBW - Yenilenebilir enerji",
        "team.role5": "Danışman",
        "team.bio5": "ÇEKÜL Vakfı - STK ve sürdürülebilirlik",
        
        // Calculator Section
        "calculator.badge": "Yatırım Hesaplayıcı",
        "calculator.title": "Yatırım Getiri Hesaplayıcı",
        "calculator.subtitle": "Potansiyel getirinizi gerçek zamanlı hesaplayın",
        "calculator.amount": "Yatırım Miktarı",
        "calculator.years": "Yatırım Süresi",
        "calculator.yearsLabel": "yıl",
        "calculator.scenario": "Senaryo",
        "calculator.total": "Toplam Getiri",
        "calculator.exit": "Çıkış Değerlemesi",
        
        // Footer
        "footer.contact": "İletişim",
        "footer.location": "İstanbul + Londra",
        "footer.legal": "Yasal",
        "footer.privacy": "Gizlilik Politikası",
        "footer.terms": "Kullanım Şartları",
        "footer.dataroom": "Data Room",
        "footer.social": "Sosyal Medya",
        "footer.copy": "© 2025 CarbonEcoMarket. Gizli ve özel doküman. Tüm hakları saklıdır."
    },
    en: {
        // Navigation
        "nav.problem": "Problem",
        "nav.solution": "Solution",
        "nav.market": "Market",
        "nav.traction": "Traction",
        "nav.financials": "Financials",
        "nav.team": "Team",
        "nav.calculator": "Calculator",
        "nav.dataroom": "Data Room Access",
        
        // Hero Section
        "hero.badge": "World's First Hybrid Carbon Exchange",
        "hero.title": "Future of Carbon Economy",
        "hero.subtitle": "CBAM 2026 compliance, blockchain verification, multi-sided marketplace leadership in $70B+ global market",
        "hero.dataroom": "Access Data Room",
        "hero.seed": "Seed Round",
        
        // Unicorn Section
        "unicorn.badge": "Unicorn Potential",
        "unicorn.title": "Path to $1B+ Valuation",
        "unicorn.subtitle": "Unique position and growth potential in global carbon market",
        "unicorn.card1.title": "$70B+ Global Market",
        "unicorn.card1.desc": "$300B+ growth projection by 2030",
        "unicorn.card2.title": "15,000+ Companies",
        "unicorn.card2.desc": "Urgent solution needed for CBAM mandate",
        "unicorn.card3.title": "Technology Leadership",
        "unicorn.card3.desc": "Blockchain + IoT + AI combination",
        "unicorn.card4.title": "4 Segment Market",
        "unicorn.card4.desc": "Individual + Farmer + Corporate + Trader",
        "unicorn.decacorn
